= Una Guía Inicial

Este capítulo te dará un vistazo general de Starling y las tecnologías con las que trabaja.
Empezaremos por tomar un pequeño vistazo a la historia de _Flash_ y _AIR_ y cómo ha surgido Starling.
Después, evaluaremos las herramientas y recursos que te ayudarán cuando trabajes con Starling.
Al final del capítulo, tendrás corriendo tu primer ejemplo de "Hola Mundo".

include::introduction.adoc[]

include::what-is-adobe-air.adoc[]

include::what-is-starling.adoc[]

include::choosing-an-ide.adoc[]

include::resources.adoc[]

include::hello-world.adoc[]

== Resumen

Ahora deberías tener una comprensión básica de Starling y las herramientas y recursos con los que vas a trabajar.
Ya sabes como conseguir e instalar el Adobe AIR SDK, y ya elegiste la IDE que mejor se adapta a tus necesidades.
La aplicación "Hello World" basada en Starling corroboró que todo está configurado correctamente.

ifdef::target-handbook[]
Es tiempo de encarar tu primer juego real!
endif::[]

ifdef::target-manual[]
Es tiempo de sumergirse en la API de Starling!
endif::[]
