== Introducción

Antes que nada: bienvenido a la comunidad Starling!
Desde su primera publicación en 2011, programadores de todo el mundo han creado juegos y aplicaciones sorprendentes con la ayuda del pequeño pájaro colorado.
Es buenísimo que quieras acompañarnos!

Has venido al lugar correcto: este manual va a enseñarte todo lo que necesitas saber.
Vamos a cubrir todo desde la 'A' de _Asset Management_ a la 'Z' de, mmm, _código-Zen_.

Comenzaré de cero, empezando con un pequeño juego que te dará una idea del framework.
Después daremos un vistazo a todos los conceptos en detalle, incluyendo la arquitectura del display list y el sistema de animación de Starling.
Capítulos posteriores contendran información para usuarios de Starling avanzados, por ejemplo, cómo escribir código para una renderización personalizada.
Antes que te des cuenta, serás un maestro en Starling!

Aunque, hay una pequeño pre-condición: Tiene que tener un conocimiento básico de _ActionScript 3_ (AS3).
No temas: si ya usaste cualquier otro lenguaje orientado a objetos, le agarrarás la mano rápidamente.
Hay muchos libros y tutoriales disponibles que te ayudarán con lo básico para empezar.

Si me preguntas por un libro en particular, te recomiendo "Essential ActionScript 3" by _Colin Moock_.
Cuando empecé a trabajar con AS3, me enseño todas las cosas importantes, y todavía me encuentro tomándolo de mi biblioteca de vez en cuando (especialmente con la sintáxis E4X tan rara que tiene AS3 para procesar documentos XML).

.AS3 vs. JS
****
Sabías que _ActionScript 3_ fue de hecho diseñado para convertirse en el sucesor de _JavaScript_?
Como deberías saber, _JavaScript_ es una implementación de la especificación de lenguaje _ECMAScript_; y _ActionScript 3_ está basado _ECMAScript 4_.
Aunque, debido mayormente a razones políticas, _ECMAScript 4_ fue abandonado y no consiguió llegar a lor navegadores web; hoy en día, _ActionScript 3_ sigue siendo la única implementación de este estándar.
Irónicamente, las versiones más modernas de _JavaScript_ se ven cada vez más similares a _ActionScript 3_.
****
