== Recursos

Ya casi tenemos todos las piezas necesarias en su lugar.
Veamos como podemos preparar todo para finalmente empezar con nuestro primero proyecto.

=== AIR SDK

Si ya elegiste e instalaste tu IDE, el próximo paso es descargarte la última versión del _AIR SDK_.
Adobe publica fielmente una nueva versión estable cada tres meses, así que estate de seguro de estar al día!
Cada nuevo lanzamiento típicamente contiene varias correcciones de errores [bug-fixes] importantes, lo que es fundamental para mantener la compatibilidad con los últimos sistemas operativos de los dispositivos móviles.
También notarás constantemente al equipo experimentando nuevas funcionalidades, de mi parte trato de seguirles el ritmo con Starling.

La última versión siempre la puedes encontrar aquí:
https://www.adobe.com/devnet/air/air-sdk-download.html[Descarga Adobe AIR SDK]

NOTE: Starling 2 requiere al menos AIR 19.

=== Flash Player Proyector

Si tu proyecto también apunta a correr en el _Flash Player_, te recomiendo que te consigas la versión autónoma [standalone], llamada _Proyector_ (disponible en versiones _Debug_ y _Release_).
La ventaja del proyector es una experiencia mucho más sencilla para la depuración.
Si, también podes depurar a través del navegador (después de instalar la version debugger del plug-in) -- pero personalmente, lo encuentro extremadamente incómodo.
El proyector se abre mucho más rápido, y no tenés que configurar ningún archivo HTML para hacerlo funcionar.

Esta página contiene una lista de todas las versiones de Flash Player aptas para desarrolladores. Busca el "projector content debugger":
https://www.adobe.com/support/flashplayer/debug_downloads.html[Descarga Adobe Flash Player Debug]

NOTE: El depurador [debugger] es significamente más lento que la versión estándar.
Tenelo en cuenta para cuando trabajes en optimizar el rendimiento.

Tu IDE podría necesitar saber cómo encontrar el reproductor correcto.
Por ejemplo, en _IDEA_, esta configuración es parte de la ventana de "debug configurations"; otras IDEs podrían simplemente usar la versión por defecto del sistema operativo.
De cualquier forma, es importante que uses siempre una versión del reproductor que sea igual o mayor a la version del AIR SDK que usaste para compilar el SWF.

=== Starling

Ahora todo lo que falta es descargar Starling.
Podes elegir entre dos formas de hacerlo.

a. Descargate la última versión como un archivo zip desde el http://gamua.com/starling/download/[website de Gamua].
b. Clona el repositorio _Git_ de Starling.

La ventaja del primero es que viene con un archivo SWC precompilado (ubicado en la carpeta `starling/bin`) que es fácil de linkear a tu proyecto.
Pero, siempre vas a encontrarte con las versiones estables de esta forma, lo que significa que te vas a perder las últimas actualizaciones de nuevas funcionalidades y arreglos!

Por esta razón, prefiero recomendar el uso de _Git_.

TIP: Digamos que reportas un error y es arreglado un par de días después (si, eso pasa seguido!): con la descarga estándar, vas a tener que esperar el arreglo hasta que genere una nueva versión estable, lo que puede significar un tiempo largo.
Cuando estás usando el repositorio _Git_, tendrás el parche disponible inmediatamente.

Meternos en profundidad sobre _Git_ iría más alla del alcance de este manual, pero encontrarás un montón de buenos tutoriales en la web.

Ya instalado, _Git_ puede _clonar_ el repositorio completo de Starling a tu disco rígido con el siguiente comando:

  git clone https://github.com/Gamua/Starling-Framework.git

Esto copiará Stalring a la carpeta `Starling-Framework`.
Encontrarás el código fuente desde de la subcarpeta `starling/src`.
Todas las IDEs mencionadas soportan agregar esta carpeta como una _ruta de código fuente_ [_source path_] a tu proyecto, lo que hará a Starling parte de tu proyecto.
Esto no es más complicado que linkear al archivo SWC; y como buen efecto secundario, vas a poder acceder al código fuente de Starling en la depuración.

Pero lo mejor de este enfoque es lo sencillo que es actualizar Stalring a su última versión.
Simplemente navega a la carpeta del repositorio y `pull`:

  cd Starling-Framework
  git pull

Eso es muchísimo más fácil que abrir el navegador y descargarte manualmente una nueva versión, no?

[NOTA]
====
Información adicional para usuarios _GIT_ avanzados:

* El desarollo del día a día de Starling acontece en el branch `master`.
* Versiones estables son _etiquetadas_ (como `v2.0`, `v2.0.1`, `v2.1`).
* Cada etiqueta es marcada como _Release_ en _GitHub_, a la cual también agregaré el archivo SWC precompilado.
====

=== Consiguiendo Ayuda

Los mejores de nosotros se atascan de vez en cuando.
Podés encontrarte con un parate por un error en Starling, o quizás por un problema que parece imposible de resolver.
De cualquier forma, la comunidad de Starling no te va a dejar solo en tu miseria!
Aquí tienes unos recursos a los que puedes asistir cuando necesites ayuda.

Foro de Starling::
Este es el centro principal de la comunidad Starling.
Con docenas de posts cada día, es muy probable de que tu problema ya haya sido consultado previamente, asi que asegurate de usar la función de _búsqueda_.
Si eso no te ayuda, sos libre de registrarte en el sitio y preguntar lo que necesites.
Una de las comunidades más amigables y pacientes que encontrarás en la web! +
-> http://forum.starling-framework.org

Manual de Starling::
ifdef::target-manual[El manual en línea que estás leyendo ahora.]
ifndef::target-manual[El manual en línea provee una extensa introducción a Starling.]
Hago lo mejor que puedo para mantenerlo actualizado con cada nueva versión. +
-> http://manual.starling-framework.org

Starling Wiki::
El wiki contiene hipervínculos y artículos sobre diferentes tópicos relacionados a Starling, y lo más importante: una lista de extensiones para Starling.
Vamos a hablar sobre eso después. +
-> http://wiki.starling-framework.org

Referencia del API::
No te olvides de consultar el API de Referencia de Starling para información detallada sobre todas las clases y métodos. +
-> http://doc.starling-framework.org

Gamua Blog::
Mantenete actualizado con las últimas novedades sobre Starling a través del blog de Gamua.
Admito que son un poco perezoso cuándo tengo que escribir blog posts, pero siempre habrá al menos uno por cada lanzamiento de Starling. +
-> http://gamua.com/blog

Twitter::
Uso varias redes sociales, pero la mejor forma de comunicarse conmigo es via `@Gamua`.
Sigue esta cuenta para recibir actualizaciones sobre new desarrollos o links a otros juegos hechos en Starling. +
-> https://twitter.com/Gamua

