== Qué es Adobe AIR?
ifndef::imagesdir[:imagesdir: ../../img]

Hace un par de años, Adobe's _Flash Player_ era omnipresente cuando navegabamos la web.
En ese entonces, era básicamente la única opción que había para crear contenidos web dinámicos o animados.
Los navegadores tenían capacidades muy limitadas en lo referente a video, sonido, y animación;
y las pocas características que tenían estaban plagadas de incompatibilidades entre los mismos.
En pocas palabras, era un desastre.

Por eso es que _Adobe Flash_ era tan popular.
Le permitía a los diseñadores y desarrolladores crear contenido multimedia en un programa de creación muy intuitivo (ahora llamado _Adobe Animate_), y eso aseguraba que se vería exactamente igual en todas las plataformas y navegadores soportados.
Con _ActionScript 3_, también se disponía de un lenguaje que era a la vez fácil de aprender y muy poderoso.

NOTE: _Flash_ fue originalmente creado por _Macromedia_, esta compañía fue comprada por Adobe en 2005.

Basándose en la popularidad de su plataforma, Adobe se dió cuenta que había una demanda de los usuarios para usar la misma tecnología para aplicaciones independientes que corriesen fuera del navegador.
Por eso existe el runtime de _Adobe AIR_.
Aplicaciones creadas con el _AIR SDK_ se pueden implementar como ejecutables independientes [standalone] que corren en el escritorio (_Windows_, _macOS_) o en dispositivos móviles (_Android_, _iOS_).

La librería estándar que contiene es un superconjunto de la que dispone Flash, por ende podés hacer cualquier cosa _AIR_ que se puede hacer en _Flash_; pero también provee un gran número de APIs adicionales para trabajar con el acceso al sistema de archivos o ventanas del sistema operativo.

Por supuesto, cuando queres crear una aplicación de escritorio, también necesitas una forma de crear interfaces de usuario gráficas, no?
Ya que la versión básica de Flash no era muy adecuada para esta tarea, decidieron moverlo a otro SDK:
_Flex_ (ahora _Apache Flex_).
Flex también introdujo un lenguaje de marcado basado en XML (llamado _MXML_) para definir diseños [layouts] de interfaces de usuario.

TIP: Para usar Starling, no necesitas _Flex_, sólo _AIR SDK_.

=== El estado actual de Flash y AIR

En el momento de su debút,  _AIR_ era parte de una tendencia resumida en un término: "Aplicaciones de Internet Enriquecidads" ["Rich Internet Applications"] (_RIA_) -- una palabra que estaba de moda y hacía furor a finales de los años 2000.

Había una feróz competencia entre Adobe's _AIR_ y Microsoft's _Silverlight_ (como también con Sun's _JavaFX_).
Avanzando rápidamente al presente, es evidente como cambió la marea.
El ganador es claramente _HTML5/JavaScript_, el cuál se convirtió en la tecnología más popular para crear aplicaciones con tecnologías web.
Hasta Adobe se sumó a la tendencia y está agregando cada vez más y más soporte _HTML5_ a sus productos.

TIP: En lo que consierne a desarrollo de software, no caigas en la trampa de seguir ciegamente a las masas.
Por cada problema, existen múltiples soluciones; algunas más convenientes que otras.
Elegí la herramienta con la que te sientas más cómodo; una herramienta que no se interponga en tu camino y te deje enfocarte en el software que queres crear.

Aunque quizás ya no sea tan popular, la plataforma __AIR/Flash__ sigue siendo extremadamente atractiva para crear aplicaciones:

* Comparada al mundo fragmentado de _HTML 5_, donde las tendencias en librerías cambian más rápido que los trajes de Lady Gaga, es muy madura y fácil de usar.
* Viene de fábrica con una extensa librería estándar que te provee de todas las herramientas que podes necesitar en el día a día.
* El plug-in de Flash, aunque claramente este en caída para desarrollo de sitios web, siguie siendo el estándar para juegos en la web.
 Por ejemplo, la mayoría de juegos en _Facebook_ siguen siendo creados en Flash.
* Especialmente cuando lo combinas con _Starling_ y _Feathers_, te provee de uno de los caminos con menos baches para crear verdaderos desarrollos multiplataforma (apuntando a las mayores plataformas de escritorio y móviles con un único código fuente).

Hablando de _Starling_ ... como calza en este panorama?
