= Conceptos Básicos

Starling puede ser un framework compacto, pero aún así contiene un número considerable de paquetes y clases.
Está armado sobre varios conceptos básicos que son diseñados para complementarse y extenderse mútuamente.
Todos juntos, te proveen de un arsenal de herramientas que te permiten crear cualquier aplicación imaginable.

Programación de Visualización:: Cada objeto que es renderizado en pantalla es un _display object_ [objeto visual], organizado en un _display list_ [lista visual].
Texturas e Imágenes:: Para traer los píxeles, formas y colores a la pantalla, necesitas aprender a usar las clases _Texture_ e _Image_.
Texto Dinámico:: La renderización de texto dinámico es una tarea básica en casi toda
aplicación.
Manejo de Eventos:: La comunicación es clave! Tus objetos visuales necesitan hablar entre ellos, y lo pueden hacer gracias al poderoso sistema de eventos de Starling.
Animación:: Usemos algo de movimiento! Exísten diferentes estratégias para animar tus objetos visuales.
Manejo de Recursos:: Aprende cómo cargar y organizar todo tipo de recursos, como texturas y sonidos.
Efectos Especiales:: Efectos y filtros que harán resaltar tus gráficos.
Utilidades:: Una variedad de clases que te ayudarána a hacer tu vida más sencilla.

Tenemos un montón de terreno por cubrir, por ende, citando a Super Mario: "Let's-a go!" [Arranquemos!]

include::configuring-starling.adoc[]

include::display-programming.adoc[]

include::textures-and-images.adoc[]

include::dynamic-text.adoc[]

include::event-handling.adoc[]

include::animations.adoc[]

include::asset-management.adoc[]

include::fragment-filters.adoc[]

include::meshes.adoc[]

include::masks.adoc[]

include::sprite3d.adoc[]

include::utilities.adoc[]

== Resúmen

Ya estás familiarizado con todos los conceptos básicos del Framework de Starling.
Este es todo el conocimiento que necesitas para empezar con ese juego que te da vueltas en tu cabeza, o con esa aplicación que está esperando a ser creada.

Pero considera que todavía hay varios trucos debajo de la manga de nuestro querido pajarito (los pájaros tiene mangas?).
Si ya te sentís listo para saltar a esos tópicos avanzados, por favor, sígueme.
